### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by ZeroCool22** [zeke/inpainter#16]
![Screenshot_6](https://user-images.githubusercontent.com/13344308/189749655-ee92a512-5974-49f3-8aea-6fabfefe369d.jpg)

![Screenshot_7](https://user-images.githubusercontent.com/13344308/189750362-4ead475c-dc3d-4c64-8aa8-9685d381c16b.jpg)

![tenorgggggg](https://user-images.githubusercontent.com/13344308/189749898-c2f3cd21-04b4-4d74-bc88-160d0f082c75.gif)

**Comment by zeke** [comment]
Ooh yikes. Did you see that more than once? Do you by any chance remember what prompt you used?

**Comment by zeke** [comment]
Closing. Let me know if you encounter this again.
