### ISSUE TITLE
How to add my API?

### ISSUE THREAD

**Issue by TotoB12** [zeke/inpainter#22]
Sorry to ask this, but can someone tell me exactly where to place my API token?

Thanks

**Comment by zeke** [comment]
Sorry that was tricky. Thanks for following up after you figured it out. 

I updated the README to make this a bit more clear: https://github.com/zeke/inpainter/commit/95f8f7a1de19322ab657d44a14496d920da636fe

**Comment by TotoB12** [comment]
Thank you so much for the clarification, it all work great!
